// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgTiA9pUJV9rfJ7HMl3NuWzufBe8SGK7s',
    appId: '1:378606769247:web:84350d21edc039dd4fb7ea',
    messagingSenderId: '378606769247',
    projectId: 'mobile-app-78d58',
    authDomain: 'mobile-app-78d58.firebaseapp.com',
    storageBucket: 'mobile-app-78d58.firebasestorage.app',
    measurementId: 'G-CVN5WX6D7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkSL99bySS0QAafqlXHsjvhK-SptkfmM',
    appId: '1:378606769247:android:d242052dd76d49194fb7ea',
    messagingSenderId: '378606769247',
    projectId: 'mobile-app-78d58',
    storageBucket: 'mobile-app-78d58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo8fRNR1wIS1-ose1_Ni2nmiBl7Z7D0ss',
    appId: '1:378606769247:ios:a02ceb724d409b104fb7ea',
    messagingSenderId: '378606769247',
    projectId: 'mobile-app-78d58',
    storageBucket: 'mobile-app-78d58.firebasestorage.app',
    iosClientId: '378606769247-jb2t9obdb9ol3q11ug49boiae2nps5o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo8fRNR1wIS1-ose1_Ni2nmiBl7Z7D0ss',
    appId: '1:378606769247:ios:a02ceb724d409b104fb7ea',
    messagingSenderId: '378606769247',
    projectId: 'mobile-app-78d58',
    storageBucket: 'mobile-app-78d58.firebasestorage.app',
    iosClientId: '378606769247-jb2t9obdb9ol3q11ug49boiae2nps5o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgTiA9pUJV9rfJ7HMl3NuWzufBe8SGK7s',
    appId: '1:378606769247:web:f5e706a8c0aac0eb4fb7ea',
    messagingSenderId: '378606769247',
    projectId: 'mobile-app-78d58',
    authDomain: 'mobile-app-78d58.firebaseapp.com',
    storageBucket: 'mobile-app-78d58.firebasestorage.app',
    measurementId: 'G-MY0JT7X1YD',
  );
}
